version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - sudo apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html 
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - aws.gif
    - back.jpg
    - buildspec.yml
    - 1.png
    - scripts/install_dependencies
    - scripts/start_server
